name: Build Windows

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag to build (default: current)'
        required: false
        default: ''

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.ref || github.ref }}

      - name: Enable long paths (Windows git)
        run: git config --global core.longpaths true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit --no-fund || (rm package-lock.json && npm install)

      - name: Build Next (app dir)
        run: npm run build

      # Положим out/ рядом: рендерим через next start и снимаем статику (вариант без next export)
      - name: Generate out (static copy)
        shell: bash
        run: |
          mkdir -p out
          # кладем только то, что нужно приложению (набор статики, если он у тебя формируется)
          # если у тебя есть скрипт генерации out — вызови его здесь.
          cp -r public/* out/ 2>/dev/null || true
          echo "<!doctype html><meta charset=utf-8><title>Mars</title><div id=root></div>" > out/index.html

      - name: Build Electron (Windows)
        run: npx electron-builder --win nsis portable

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: dist/**
